# Generated by Django 5.2.5 on 2025-09-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('shorts', 'Shorts'), ('shoes', 'Shoes'), ('tracksuit', 'Tracksuit'), ('accessories', 'Accessories'), ('equipment', 'Equipment')], default='jersey', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], default='M', max_length=10)),
                ('gender', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex'), ('kids', 'Kids')], default='unisex', max_length=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
