# Generated by Django 5.2.5 on 2025-09-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_color_products_sold_count_alter_products_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_group',
            field=models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('badminton', 'Badminton'), ('volleyball', 'Volleyball'), ('running', 'Running'), ('gym', 'Gym/Fitness')], default='running', max_length=20),
        ),
    ]
